### ISSUE TITLE
Missing references

### ISSUE THREAD

**Issue by beatrizserrano** [beatrizserrano/bh2023-preprint#3]
@matuskalas I've removed Euro-BioImaging as a reference cause there's no paper for this. 
The missing ones are now related to Zarr, NCZarr and GeoZarr, which have no papers, here are the links provided by Anne:
https://github.com/zarr-developers/geozarr-spec
https://docs.unidata.ucar.edu/nug/current/nczarr_head.html
https://zarr-specs.readthedocs.io/en/latest/specs.html

Are there more refs to add? Generated pdf looks nice :)

**Comment by annefou** [comment]
I don't think so.

**Comment by matuskalas** [comment]
Alright, thanks. Then I'll do my revision of the text. I'll add those links where needed then.

**Comment by matuskalas** [comment]
The current PDF is visible here: http://preview.biohackrxiv.org/papers/1667a6a1-7ccf-4988-b9b3-696801e9d810/paper.pdf THE MANUSCRIPT LOOKS SO AWESOME, great work all!!!! ❤

Please review whether there's something you want to improve @beatrizserrano @annefou _et al._. Maybe the overflown courier text? And please fill in missing stuff, such as the affiliations, thanks!! 🙏🏽🙇🏽‍♂️

I'll review the rest of text when I find time during the weekend.

**Comment by beatrizserrano** [comment]
Thank you so much for the improvements :) 

> Maybe the overflown courier text? 

Isn't that supposed to be rendered as a graph?

**Comment by beatrizserrano** [comment]
> And please fill in missing stuff, such as the affiliations, thanks!! 🙏🏽🙇🏽‍♂️

Fixed [here](https://github.com/beatrizserrano/bh2023-preprint/pull/5)
