### ISSUE TITLE
Mermaid graph not rendered

### ISSUE THREAD

**Issue by beatrizserrano** [beatrizserrano/bh2023-preprint#7]
When generating the [preview](http://preview.biohackrxiv.org/papers/c30de3f0-da37-4eea-836d-51f33bff06e6/paper.pdf), the mermaid graph does not appear rendered, resulting in an overflow of text that does not help the readability of the manuscript at all. Should we simply remove it?

**Comment by beatrizserrano** [comment]
Removing it has the extra advantage that the pie chart from Leonid would fit into the page :)

**Comment by kostrykin** [comment]
I think it's fine to remove it. Alternative would be to render it manually and insert a PNG / EPS / SVG.

**Comment by beatrizserrano** [comment]
I've deleted it and it looks better now: http://preview.biohackrxiv.org/papers/a1840a1d-32cd-40bf-8d43-6d10aeed76b1/paper.pdf
