### ISSUE TITLE
[not crucial] Preference of EDAM annotations

### ISSUE THREAD

**Issue by matuskalas** [beatrizserrano/bh2023-preprint#9]
"We point out that there is a global list of precedential [Bio.tools](https://bio.tools/) [@citesAsAuthority:usesDataFrom:biotools] annotations in Galaxy, which outweighs the annotations made in the XML specification of a Galaxy tool"

I might be completely wrong (or my brain doesn't work anymore on Sunday 1am), but I thought it was the other way round, i.e. that the EDAM annotations in the XML of a wrapper have higher priority than those in Bio.tools. @pauzierep @bebatut what's correct?

But in any case, I fully agree that this is subject to change, and if possible should be treated so. 👍🏽👍🏽 So a low-priority issue, just that ideally we shouldn't state something not true in the preprint.

**Comment by beatrizserrano** [comment]
@kostrykin @bgruening do you know this?

**Comment by kostrykin** [comment]
I think the confusion is due to two things being confused here 🤓

I remember that we had discussed this topic, and, as far as I remember, the bottom line of the discussion was indeed that the annotations in the XML have _lower_ priority than those defined in Galaxy (there is a file, which defines the annotations for specific tools). I don't remember now which file this was,  but, to my knowledge, this has nothing to do with bio.tools.

And then there _is_ bio.tools. As far as I know, the EDAM annotations are fetched from bio.tools for tool wrappers, which do not have any annotations defined.

<sup>____________________________________<br>Update: I have minority revised the text above since it looks like I also have confused a few things 😅</sup>

**Comment by matuskalas** [comment]
Quadrillion thanks @kostrykin 🙏🏽🙏🏽🙇🏽‍♂️ This is exactly how I remembered it too!

**Comment by matuskalas** [comment]
And sorry all, I forgot where to search for the "global Galaxy" list of annotations. Would you mind adding a link to it into the text here:

"We point out that there is a global list of precedential annotations with [Bio.tools](https://bio.tools/) identifiers [@citesAsAuthority:usesDataFrom:biotools] in Galaxy (LINK HERE PLEASE), which ..."

I don't insist on this, but I think it would avoid others' confusion, and perhaps also our own in the future 😅

**Comment by beatrizserrano** [comment]
Could be [this one](https://github.com/galaxyproject/galaxy/blob/1abf45f537499d4d972eadc3fccd838dd9cb0505/lib/galaxy/tool_util/ontologies/biotools_mappings.tsv)?

**Comment by kostrykin** [comment]
I think it's it, but I'm not entirely sure and it would be good to verify somehow before pasting this link into the report.

Not quite sure now, however, how we could verify this.

**Comment by matuskalas** [comment]
Yes, that looks familiar! So I assume it's the correct one :D
https://github.com/galaxyproject/galaxy/blob/dev/lib/galaxy/tool_util/ontologies/biotools_mappings.tsv
In the default branch, it is the above 👆🏽

**Comment by beatrizserrano** [comment]
I've asked @bgruening for confirmation. And then I'll edit the text accordingly

**Comment by beatrizserrano** [comment]
Bjorn confirms that the link is correct

**Comment by matuskalas** [comment]
Million thanks all! 🙏🏽🙏🏽🙇🏽‍♂️👾🦑🐙
Submit?

**Comment by beatrizserrano** [comment]
I just finished the submission! But requires moderation, so won't have the doi for the BH project submission I guess :(

So, for now, all we have is this: https://github.com/elixir-europe/biohackathon-projects-2023/blob/main/16/BH2023_preprint_project16.pdf

**Comment by matuskalas** [comment]
Billion thanks @beatrizserrano and all! 🙏🏽🙏🏽

In the end it was quite quick, https://doi.org/10.37044/osf.io/w8dsz.

What is the status of the BH proposal?

**Comment by beatrizserrano** [comment]
I submitted in the afternoon :)
